modLoader="javafml"
loaderVersion = "[47,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "gtceu"
mandatory = false
versionRange = "[7.1.3,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ae2"
mandatory = false
versionRange = "[15.4.2,)"
ordering = "AFTER"
side = "BOTH"
